version: '3.5'

services:
  contracts-env:
    env_file:
      - .env
    build:
      context: ./
    working_dir: /src
    command: npm run run-env
    volumes:
      - ./:/src
    environment:
      MNEMONIC: ${MNEMONIC}
      SMARTSCAN_KEY: ${SMARTSCAN_KEY}
      SMARTSCAN_NETWORK: ${SMARTSCAN_NETWORK}
      ALCHEMY_KEY: ${ALCHEMY_KEY}
      DEFENDER_API_KEY: ${DEFENDER_API_KEY}
      DEFENDER_SECRET_KEY: ${DEFENDER_SECRET_KEY}
